services:
  app:
    image: 'hello-world:latest'
    asdkfjaskldf
  # server:
  #   image: 'hashicorp/http-echo'
  #   ports:
  #     - 9877:8080
  #   command: '-listen=:8080 -text=owo'

  # app:
  #   image: 'benricheson101/watchtower-test:latest'
