on:
  workflow_call:
    inputs:
      should_push:
        type: 'boolean'
        default: false

jobs:
  build_docker:
    permissions:
      packages: 'write'
      contents: 'read'

    name: 'Build Docker images'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v4'

      - run: |
          docker compose build
          # docker build . -t benricheson101/echo-server

      - name: 'Log in to the Container registry'
        if: inputs.should_push
        uses: 'docker/login-action@v1'
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'Push Docker images'
        if: inputs.should_push
        run: |
          docker compose push
