on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: 'string'
      compose_project_name:
        required: true
        type: 'string'

    secrets:
      ssh_private_key:
        required: true
      ssh_host:
        required: true
      ssh_user:
        required: true

jobs:
  configure:
    name: 'Configure SSH'
    runs-on: 'ubuntu-latest'
    environment: '${{inputs.environment}}'

    steps:
      - name: 'Write SSH keys'
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{secrets.ssh_private_key}}" > ~/.ssh/id_ed25519
          ssh-keyscan -H "${{secrets.ssh_host}}" > ~/.ssh/known_hosts

      - name: 'Create Docker context'
        run: |
          docker context create remote --docker 'host=ssh://${{secrets.ssh_user}}@${{secrets.ssh_host}}'

      - uses: 'actions/checkout@v4'

      - name: 'Deploy'
        env:
          COMPOSE_PROJECT_NAME: '${{vars.compose_project_name}}'
        run: |
          docker context use remote
          docker compose pull
          docker compose -f docker-compose.yml up -d

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
