on:
  push:
    branches:
      - 'main'
      - 'staging'

jobs:
  deploy_staging:
    name: 'Deploy to Staging'
    uses: './.github/workflows/deployer.yml'
    secrets: inherit
    with:
      environment: 'staging'
      compose_project_name: '${{vars.COMPOSE_PROJECT_NAME}}-staging'

  deploy_prod:
    name: 'Deploy to Production'
    if: github.ref == 'refs/heads/main'
    needs: ['deploy_staging']
    uses: './.github/workflows/deployer.yml'
    secrets: inherit
    with:
      environment: 'prod'
      compose_project_name: '${{vars.COMPOSE_PROJECT_NAME}}'

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
