on:
  push:
    branches:
      - 'main'
      - 'staging'

jobs:
  build_and_push_docker:
    if: github.ref == 'refs/heads/main'
    permissions:
      packages: 'write'
      contents: 'read'

    uses: './.github/workflows/builder.yml'
    with:
      should_push: "${{github.ref == 'refs/heads/main'}}"

  deploy_staging:
    name: 'Deploy to Staging'
    needs:
      - 'build'
    uses: './.github/workflows/deployer.yml'
    secrets: inherit
    with:
      environment: 'staging'
      compose_project_name: '${{vars.COMPOSE_PROJECT_NAME}}-staging'
      build_compose_images: true

  deploy_prod:
    name: 'Deploy to Production'
    permissions:
      packages: 'write'
      contents: 'read'

    if: github.ref == 'refs/heads/main'
    needs:
      - 'deploy_staging'
      - 'build_and_push_docker'
    uses: './.github/workflows/deployer.yml'
    secrets: inherit
    with:
      environment: 'prod'
      compose_project_name: '${{vars.COMPOSE_PROJECT_NAME}}'

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
