on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: 'string'
      compose_project_name:
        required: true
        type: 'string'
      build_compose_images:
        required: false
        type: 'boolean'
        default: false

    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  configure:
    name: 'Configure SSH'
    runs-on: 'ubuntu-latest'
    environment: '${{inputs.environment}}'

    steps:
      - name: 'Write SSH keys'
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
          ssh-keyscan -H "${{secrets.SSH_HOST}}" > ~/.ssh/known_hosts

      - name: 'Create Docker context'
        run: |
          docker context create remote --docker 'host=ssh://${{secrets.SSH_USER}}@${{secrets.ssh_host}}'

      - name: 'Deploy'
        env:
          COMPOSE_PROJECT_NAME: '${{inputs.compose_project_name}}'
        run: |
          docker context use remote
          # docker compose pull

          if [ ${{inputs.build_compose_images}} = true ]; then
            docker compose -f docker-compose.yml up -d --remove-orphans --build
          else
            docker compose -f docker-compose.yml up -d --remove-orphans
          fi

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
