on:
  push:
    branches: ['main']

jobs:
  deploy_prod:
    name: 'Deploy to Production'
    # runs-on: 'ubuntu-latest'
    # environment:
    #   name: 'prod'
    #   url: 'https://puy.gay'

    uses: './.github/workflows/deployer.yml'
    secrets: inherit
    with:
      environment: 'prod'
      compose_project_name: '${{vars.COMPOSE_PROJECT_NAME}}'


    # steps:
    #   - name: 'does this even run???'
    #     run: "echo 'HELLO???'"

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
